#!/usr/bin/env python3
"""
Asset pipeline for esp32-vibe-companion.

Reads the source images from ~/Downloads/deskbot-art/ (or --src DIR),
center-crops each to 135x240, converts to RGB565, and emits ../sprites.h with
one PROGMEM array per mood plus an enum + accessor.

Filename matching is intentionally forgiving: filenames in the wild contain
typos ("botmadangry.jpg") and Unicode lookalike separators
("spriteblush<U+2044>dizzy.jpg"), so we normalize every name to
[lowercase ascii alphanumerics only] and then match the most specific
keyword first (e.g. PROUD/"happypointingtoself" is tested before
HAPPY/"happy", otherwise the generic keyword would steal it).
"""

import argparse
import json
import os
import re
import sys
import unicodedata

try:
    from PIL import Image
except ImportError:  # pragma: no cover
    sys.exit("Pillow is required:  python3 -m pip install --user Pillow")

WIDTH, HEIGHT = 135, 240

# Mood name -> substring that must appear in the source filename.
#
# The defaults assume your art is named after the mood (happy.png, angry.png).
# If your files are named differently, put the real mapping in a JSON file and
# pass --map (see mood_map.json.example). A mood_map.json sitting next to this
# script is picked up automatically and is gitignored, so your own filenames
# never enter the repository.
#
# Order matters: kept most-specific-first, so a generic key cannot steal a
# specific match. Each source file is claimed by at most one mood.
MOOD_RULES = [
    ("HEART",         "heart"),
    ("CONFUSED",      "confused"),
    ("SLEEPING",      "sleeping"),
    ("SCHEMING",      "scheming"),
    ("BLANKET",       "blanket"),
    ("INTENSE",       "intense"),
    ("LEANING",       "leaning"),
    ("CASUAL",        "casual"),
    ("CLOSEUP",       "closeup"),
    ("PLAYFUL",       "playful"),
    ("ANGRY",         "angry"),
    ("CONFIDENT",     "confident"),
    ("POUT",          "pout"),
    ("BLUSH",         "blush"),
    ("PROUD",         "proud"),
    ("NO_INTERNET",   "nointernet"),
    ("SMUG",          "smug"),
    ("HAPPY",         "happy"),
]

# Enum order = runtime mood indexing order.
MOOD_ORDER = [m for m, _ in MOOD_RULES]


def load_mood_map(path):
    """Override the mood mapping and source dir from a JSON map. Returns src."""
    global MOOD_RULES, MOOD_ORDER
    if not path or not os.path.isfile(path):
        return None
    with open(path) as fh:
        cfg = json.load(fh)
    if cfg.get("moods"):
        MOOD_RULES = [(str(m), str(k)) for m, k in cfg["moods"].items()]
        MOOD_ORDER = [m for m, _ in MOOD_RULES]
    return cfg.get("src")


def normalize(name):
    """'spriteblush\u2044dizzy.jpg' -> 'spriteblushdizzyjpg'"""
    name = unicodedata.normalize("NFKD", name)
    name = name.encode("ascii", "ignore").decode("ascii")
    name = name.lower()
    return re.sub(r"[^a-z0-9]", "", name)


def find_sources(src_dir):
    """Return {mood: (filename, abspath)} using most-specific-keyword-first."""
    files = [f for f in sorted(os.listdir(src_dir))
             if f.lower().endswith((".jpg", ".jpeg", ".png", ".bmp", ".webp"))]
    normed = [(f, normalize(f)) for f in files]

    found, claimed = {}, set()
    for mood, keyword in MOOD_RULES:
        match = None
        for f, norm in normed:
            if f in claimed:
                continue
            if keyword in norm:
                match = (f, os.path.join(src_dir, f))
                break
        if match:
            found[mood] = match
            claimed.add(match[0])

    missing = [m for m, _ in MOOD_RULES if m not in found]
    if missing:
        print(f"[!] no image matched for moods: {missing}", file=sys.stderr)
        print(f"    files seen: {files}", file=sys.stderr)
    return found


def center_crop_resize(img, w=WIDTH, h=HEIGHT):
    """Scale to cover w x h, then center-crop to exactly w x h. LANCZOS."""
    img = img.convert("RGB")
    src_w, src_h = img.size
    scale = max(w / src_w, h / src_h)
    new_size = (max(w, int(round(src_w * scale))), max(h, int(round(src_h * scale))))
    img = img.resize(new_size, Image.LANCZOS)
    left = (img.size[0] - w) // 2
    top = (img.size[1] - h) // 2
    return img.crop((left, top, left + w, top + h))


def to_rgb565(img):
    """Return a flat list of RGB565 uint16 values."""
    px = img.load()
    out = []
    for y in range(img.size[1]):
        for x in range(img.size[0]):
            r, g, b = px[x, y]
            out.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))
    return out


def emit_header(arrays, path, src_dir):
    with open(path, "w") as fh:
        fh.write("// AUTO-GENERATED by scripts/convert_images.py -- do not edit by hand.\n")
        fh.write(f"// Source: {src_dir}\n")
        fh.write(f"// {len(arrays)} sprites, {WIDTH}x{HEIGHT} RGB565 "
                 f"({WIDTH * HEIGHT * 2} bytes each, "
                 f"{len(arrays) * WIDTH * HEIGHT * 2} bytes total).\n")
        fh.write("//\n")
        fh.write("// Stored as native-endian uint16_t RGB565. The firmware calls\n")
        fh.write("// tft.setSwapBytes(true) before pushImage() so TFT_eSPI emits the\n")
        fh.write("// big-endian byte order the ST7789 controller expects -- equivalent to\n")
        fh.write("// pre-swapping every byte pair, but 2x smaller in flash.\n\n")
        fh.write("#pragma once\n#include <Arduino.h>\n\n")
        fh.write(f"#define SPRITE_W {WIDTH}\n#define SPRITE_H {HEIGHT}\n\n")

        fh.write("enum Mood : uint8_t {\n")
        for i, mood in enumerate(MOOD_ORDER):
            fh.write(f"  MOOD_{mood} = {i},\n")
        fh.write(f"  MOOD_COUNT = {len(MOOD_ORDER)}\n}};\n\n")

        for mood in MOOD_ORDER:
            if mood not in arrays:
                continue
            vals = arrays[mood]
            fh.write(f"// {mood}\nconst uint16_t {mood.lower()}_sprite"
                     f"[{len(vals)}] PROGMEM = {{\n")
            for i in range(0, len(vals), 12):
                fh.write("  " + ",".join(f"0x{v:04X}" for v in vals[i:i + 12]) + ",\n")
            fh.write("};\n\n")

        # name table + accessor
        fh.write("inline const char* moodName(Mood m) {\n  switch (m) {\n")
        for mood in MOOD_ORDER:
            fh.write(f'    case MOOD_{mood}: return "{mood}";\n')
        fh.write('    default: return "HAPPY";\n  }\n}\n\n')

        fh.write("inline const uint16_t* getSprite(Mood m) {\n  switch (m) {\n")
        for mood in MOOD_ORDER:
            if mood in arrays:
                fh.write(f"    case MOOD_{mood}: return {mood.lower()}_sprite;\n")
        fh.write("    default: return happy_sprite;\n  }\n}\n")


def emit_photos(images, path, scale=0.66, quality=78):
    """Emit photos.h -- one JPEG per mood, for sending back over Telegram.

    Telegram needs a real image file, and UniversalTelegramBot's
    sendPhotoByBinary() streams one from memory via callbacks, so embedding the
    JPEGs in PROGMEM avoids needing a filesystem partition entirely.

    The Telegram copies are deliberately SCALED DOWN from the panel sprites: the
    panel needs 135x240, but a chat photo at that size occupies a lot of vertical
    space on a phone for no benefit, so we send a smaller one (and a smaller file
    to upload). Tune with --telegram-scale / --telegram-quality.
    """
    import io

    tw = max(1, int(round(WIDTH * scale)))
    th = max(1, int(round(HEIGHT * scale)))

    with open(path, "w") as fh:
        fh.write("// AUTO-GENERATED by scripts/convert_images.py -- do not edit.\n")
        fh.write("// Small JPEGs of each mood, sent back over Telegram via\n")
        fh.write("// bot.sendPhotoByBinary() so the chat matches the panel.\n")
        fh.write("// PROGMEM, not a filesystem: no partition changes needed.\n")
        fh.write(f"// Scaled to {tw}x{th} (panel sprites are {WIDTH}x{HEIGHT}).\n\n")
        fh.write("#pragma once\n#include <Arduino.h>\n#include \"sprites.h\"\n\n")

        sizes = {}
        for mood in MOOD_ORDER:
            if mood not in images:
                continue
            buf = io.BytesIO()
            images[mood].resize((tw, th), Image.LANCZOS).save(
                buf, format="JPEG", quality=quality, optimize=True,
                progressive=False)
            data = buf.getvalue()
            sizes[mood] = len(data)
            fh.write(f"// {mood}: {len(data)} bytes\n")
            fh.write(f"const uint8_t photo_{mood.lower()}[] PROGMEM = {{\n")
            for i in range(0, len(data), 16):
                fh.write("  " + ",".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",\n")
            fh.write("};\n\n")

        fh.write("struct MoodPhoto { const uint8_t* data; uint32_t len; };\n\n")
        fh.write(f"static const MoodPhoto MOOD_PHOTOS[MOOD_COUNT] PROGMEM = {{\n")
        for mood in MOOD_ORDER:
            if mood in sizes:
                fh.write(f"  {{ photo_{mood.lower()}, sizeof(photo_{mood.lower()}) }},"
                         f"  // {sizes[mood]} B\n")
        fh.write("};\n")

    total = sum(sizes.values())
    avg = total / max(1, len(sizes))
    print(f"wrote {path}  ({len(sizes)} JPEGs at {tw}x{th}, {total} bytes, "
          f"avg {avg:.0f} B each)")


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=None,
                    help="directory of source images (default: from the map file, "
                         "else ~/Downloads/deskbot-art)")
    ap.add_argument("--map", default=os.path.join(here, "mood_map.json"),
                    help="JSON mood mapping, optional src (see mood_map.json.example)")
    ap.add_argument("--out", default=os.path.join(here, "..", "sprites.h"))
    ap.add_argument("--photos-out", default=os.path.join(here, "..", "photos.h"))
    ap.add_argument("--telegram-scale", type=float, default=0.66,
                    help="scale factor for the Telegram JPEGs (smaller = tidier in chat)")
    ap.add_argument("--telegram-quality", type=int, default=78,
                    help="JPEG quality for the Telegram copies")
    ap.add_argument("--preview-dir", default=os.path.join(here, "..", "preview"))
    args = ap.parse_args()

    src_from_map = load_mood_map(args.map)
    if args.src is None:
        args.src = src_from_map or os.path.expanduser("~/Downloads/deskbot-art")

    if not os.path.isdir(args.src):
        sys.exit(f"source directory not found: {args.src}")

    found = find_sources(args.src)
    if not found:
        sys.exit("no source images matched any mood keyword")

    os.makedirs(args.preview_dir, exist_ok=True)
    arrays = {}
    images = {}
    print(f"{'MOOD':<12} {'SOURCE FILE':<38} SIZE")
    for mood in MOOD_ORDER:
        if mood not in found:
            continue
        filename, path = found[mood]
        img = center_crop_resize(Image.open(path))
        images[mood] = img
        arrays[mood] = to_rgb565(img)
        img.save(os.path.join(args.preview_dir, f"{mood.lower()}.png"))
        print(f"{mood:<12} {filename:<38} {img.size}")

    emit_header(arrays, os.path.abspath(args.out), args.src)
    emit_photos(images, os.path.abspath(args.photos_out),
                args.telegram_scale, args.telegram_quality)
    total = len(arrays) * WIDTH * HEIGHT * 2
    print(f"\nwrote {os.path.abspath(args.out)}  "
          f"({len(arrays)} sprites, {total} bytes = {total / 1024:.0f} KB of PROGMEM)")
    print(f"previews -> {os.path.abspath(args.preview_dir)}")


if __name__ == "__main__":
    main()
